const schemas = {
  agency: [
    'agency_id',
    'agency_name',
    'agency_url',
    'agency_timezone',
    'agency_lang',
    'agency_phone',
    'agency_fare_url',
    'agency_email',
    'import_package',
  ],
  stops: [
    'stop_id',
    'stop_code',
    'stop_name',
    'stop_desc',
    'stop_lat',
    'stop_lon',
    'zone_id',
    'stop_url',
    'location_type',
    'parent_station',
    'stop_timezone',
    'wheelchair_boarding',
    'import_package',
  ],
  routes: [
    'route_id',
    'agency_id',
    'route_short_name',
    'route_long_name',
    'route_desc',
    'route_type',
    'route_url',
    'route_color',
    'route_text_color',
    'import_package',
  ],
  trips: [
    'route_id',
    'service_id',
    'trip_id',
    'trip_headsign',
    'trip_short_name',
    'direction_id',
    'block_id',
    'shape_id',
    'wheelchair_accessible',
    'bikes_allowed',
    'consist',
    'set_type',
    'import_package',
  ],
  stop_times: [
    'trip_id',
    'arrival_time',
    'departure_time',
    'arrival_time_24',
    'departure_time_24',
    'stop_id',
    'stop_sequence',
    'stop_headsign',
    'pickup_type',
    'drop_off_type',
    'shape_dist_traveled',
    'timepoint',
    'import_package',
  ],
  calendar: [
    'service_id',
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday',
    'start_date',
    'end_date',
    'import_package',
  ],
  calendar_dates: ['service_id', 'date', 'exception_type', 'import_package'],
  transfers: [
    'from_stop_id',
    'to_stop_id',
    'transfer_type',
    'min_transfer_time',
    'import_package',
  ],
  frequencies: [
    'trip_id',
    'start_time',
    'end_time',
    'headway_sec',
    'exact_times',
    'import_package',
  ],
}

export default schemas
